import Header from "./components/Header";
import { ApolloProvider, ApolloClient, InMemoryCache } from "@apollo/client";
import Clients from "./components/Clients";
import AddClientModal from "./components/AddClientModal";

// fixing warning generated by updating UI after deleting a client/project
const cache = new InMemoryCache({
	typePolicies: {
		Query: {
			fields: {
				clients: {
					merge(existing, incoming) {
						return incoming;
					},
				},
				projects: {
					merge(existing, incoming) {
						return incoming;
					},
				},
			},
		},
	},
});

const client = new ApolloClient({
	uri: "http://localhost:5000/graphql",
	cache,
});

function App() {
	return (
		<>
			<ApolloProvider client={client}>
				<Header />
				<div className="container">
					<AddClientModal />
					<Clients />
				</div>
			</ApolloProvider>
		</>
	);
}

export default App;
